# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppClusteringEMGlassoWeighted <- function(InputList, l, r, Pk_in, tol = 1e-3, max_iter = 250L, inner_warm_start = FALSE, predecessor_fitted = FALSE) {
    .Call(`_SelvarMixMNAR_rcppClusteringEMGlassoWeighted`, InputList, l, r, Pk_in, tol, max_iter, inner_warm_start, predecessor_fitted)
}

rcppDiscriminantAnalysisGlasso <- function(X_, labels_, nbClust, l, r) {
    .Call(`_SelvarMixMNAR_rcppDiscriminantAnalysisGlasso`, X_, labels_, nbClust, l, r)
}

LoglikelihoodObsGaussian <- function(YNA, mu, sigma, alpha, prop_pi) {
    .Call(`_SelvarMixMNAR_LoglikelihoodObsGaussian`, YNA, mu, sigma, alpha, prop_pi)
}

InitEMGaussian <- function(YNA, K, mecha, diag, init, samplesize) {
    .Call(`_SelvarMixMNAR_InitEMGaussian`, YNA, K, mecha, diag, init, samplesize)
}

MechanismEMGLM <- function(YNA, tik, mecha) {
    .Call(`_SelvarMixMNAR_MechanismEMGLM`, YNA, tik, mecha)
}

EMGaussian <- function(YNA, K, mecha, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call(`_SelvarMixMNAR_EMGaussian`, YNA, K, mecha, diag, rmax, init, tol, samplesize)
}

LoglikelihoodObsGaussianMixed <- function(YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list = NULL, E_sig_list = NULL) {
    .Call(`_SelvarMixMNAR_LoglikelihoodObsGaussianMixed`, YNA, mu, sigma, alpha, beta, prop_pi, is_mnar, E_mu_list, E_sig_list)
}

InitEMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, init, samplesize) {
    .Call(`_SelvarMixMNAR_InitEMGaussianMixed`, YNA, K, mecha, is_mnar, diag, init, samplesize)
}

MechanismEMGLMMixed <- function(YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta) {
    .Call(`_SelvarMixMNAR_MechanismEMGLMMixed`, YNA, tik, mecha, is_mnar, E_y_list, current_alpha, current_beta)
}

EMGaussianMixed <- function(YNA, K, mecha, is_mnar, diag, rmax, init = NULL, tol = 0.0001, samplesize = NULL) {
    .Call(`_SelvarMixMNAR_EMGaussianMixed`, YNA, K, mecha, is_mnar, diag, rmax, init, tol, samplesize)
}

rcppSelectS <- function(X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA, stoppingRule = "consecutive") {
    .Call(`_SelvarMixMNAR_rcppSelectS`, X, Order, nbCluster, framework, model_name, packSize, Crit, knownlabels, DA, stoppingRule)
}

rcppSelectW <- function(X, Order, OtherVar, packSize, stoppingRule = "consecutive") {
    .Call(`_SelvarMixMNAR_rcppSelectW`, X, Order, OtherVar, packSize, stoppingRule)
}

rcppSelectR <- function(X, S, U, regmodel) {
    .Call(`_SelvarMixMNAR_rcppSelectR`, X, S, U, regmodel)
}

rcppSelectionTrace <- function(differences, c, stoppingRule = "consecutive", direction = "forward") {
    .Call(`_SelvarMixMNAR_rcppSelectionTrace`, differences, c, stoppingRule, direction)
}

rcppRegressionBIC <- function(X, response, predictors, model) {
    .Call(`_SelvarMixMNAR_rcppRegressionBIC`, X, response, predictors, model)
}

rcppCrit <- function(X, MyList, rgm, idm) {
    .Call(`_SelvarMixMNAR_rcppCrit`, X, MyList, rgm, idm)
}

